### ISSUE TITLE
Spaces counted as words bug?

### ISSUE THREAD

**Issue by codygman** [chaosparrot/talon_practice#1]
Are spaces supposed to be counted as words in those talon practice exercises? Maybe this is platform specific, but for instance and slack right now if from the beginning of this message I say go word right second I end up at `Are spaces| supposed` it but in the exercises text box I end up like this: `Are |spaces supposed`.

Originally posted in: https://talonvoice.slack.com/archives/C7ERD5Q5T/p1621630193070700

**Comment by chaosparrot** [comment]
Hey! 

By default, what go word right does is press Ctrl + right , as per the knausj repository. However, the result of what ctrl + right does depends on the program, which can make the behavior inconsistent across programs even though the text is the same.

For example, if I press ctrl right in a program like NotePad++, it will also stop at the dots in my code, whereas using the command on the same piece of text in Google Chrome would skip past it. 

There are ways to make it more consistent, but that would require changing python code in knausj, and if a program isn't specifically targeted to override the behavior, it would ultimately still be inconsistent.

I hope this has clarified some things, I will close this issue now. Let me know if there are other things that require more explanation :)
