### ISSUE TITLE
Using your mouse: instructions to turn on mouse grid

### ISSUE THREAD

**Issue by erhoppe** [chaosparrot/talon_practice#2]
The settings have changed, presumably since this was written, and the line to uncomment to enable the mouse grid is now line 51 (not 25 as described). It would also be helpful to give a description that it starts with tag or something. :)

**Comment by chaosparrot** [comment]
Thanks for filing the issue! I'll do a quick check on the latest knausj_talon to see if other things have gotten changed in the meantime and change any other changes that have happened since I last updated this.

**Comment by chaosparrot** [comment]
I fixed the line and also came across an update with regards to the media commands, so I changed that as well. It should be up on the github page soon enough!

**Comment by erhoppe** [comment]
Thanks for updating it so quickly and for making/maintaining such a great resource!
