### ISSUE TITLE
"Show help" button doesn't seem to do anything

### ISSUE THREAD

**Issue by bitwombat** [chaosparrot/talon_practice#4]
Hi - The "Show help" button appears to be pressable (turns blue), and will turn off if I "Start game", but doesn't ever seem to change the page.

I was thinking it might show the lesson while the game is running.

No console messages, no assets 404.

Linux, Firefox and Chrome (no plugins).

**Comment by chaosparrot** [comment]
Sorry for not taking the time to answer this sooner. I will take a look at trying to repro this this week.

**Comment by chaosparrot** [comment]
I fixed this in the latest master for the non-challenge mode ( which is the default ). It's still broken to a certain extent in challenge mode, but I consider that mode to be a bit more unforgiving to make memorization more important.
