### ISSUE TITLE
The yellow text used for highlighting certain words is really hard to pick out.

### ISSUE THREAD

**Issue by AndrewDant** [chaosparrot/talon_practice#5]
I find it very difficult to decipher which words are emphasized via the use of yellow text. It makes it harder to read and learn when you can't quite tell which words are emphasized or not. With your permission I'd like to make a pull request changing all of the yellow text to bold, italics, or a more discernible color.

**Comment by AndrewDant** [comment]
Here is a before:
![image](https://user-images.githubusercontent.com/30133577/145150128-84149f11-54a8-47dd-9787-91e39e4d5161.png)

and here is after:
![image](https://user-images.githubusercontent.com/30133577/145150147-a2d79474-11a5-4048-809b-4b254788c8fd.png)

**Comment by chaosparrot** [comment]
Thank you for taking the time to change this around and showing off the screenshots. I agree that your solution offers a better emphasis on the commands, which is what I was going for with the yellow text trying to contrast it with the blue background.

If you make a PR, I will be sure to merge it.
