### ISSUE TITLE
Browsing the web reload/refresh commands missing "it"

### ISSUE THREAD

**Issue by AndrewDant** [chaosparrot/talon_practice#7]
The browsing the web page lists the commands "reload" and "refresh" however the commands seem to actually be "reload it" and "refresh it" as shown in this screenshot snippet.
![image](https://user-images.githubusercontent.com/30133577/145281216-46006b63-37ad-4a2f-a310-34f2adea8327.png)

**Comment by chaosparrot** [comment]
I'll change it this weekend, thanks for the heads up!

**Comment by chaosparrot** [comment]
This is fixed in the latest master
